export const SKILLS = "SKILLS PAGE";
export const SOFTSKILLS = "SOFT-SKILLS PAGE";
export const EDUCATION = "EDUCATION PAGE";
export const EXPERIENCE = "EXPERIENCE PAGE";
export const HOBBIES = "HOBBIES PAGE";
export const ENVIRONMENT = "ENVIRONMENT PAGE";

export const PAGE_ACTION = 'PAGE_ACTION';